Massive Bookshelf Sync
MinecraftModDevelopment/MMDLib pull request #6
Opened 2016-12-28 21:43 UTC by darkhax

2016-12-30 17:44 UTC, adrwa requested changes

2016-12-30 17:44 UTC, TheCodedOne commented on src/main/java/com/mcmoddev/lib/client/gui/GuiButtonGraphical.java
> -@SideOnly(Side.CLIENT)
This should be side only

2016-12-30 17:44 UTC, TheCodedOne commented on src/main/java/com/mcmoddev/lib/client/gui/GuiButtonGraphical.java
> +
Can we do something about the formatting

2016-12-31 22:54 UTC, darkhax commented on src/main/java/com/mcmoddev/lib/client/gui/GuiButtonGraphical.java
> -@SideOnly(Side.CLIENT)
Button is now client side again.

2016-12-31 22:54 UTC, darkhax commented on src/main/java/com/mcmoddev/lib/client/gui/GuiButtonGraphical.java
> +
Will do in seperate PR to avoid merge conflicts.

2017-01-01 11:35 UTC, adrwa approved these changes

2017-01-01 11:35 UTC, merged